spring:
  config:
    import:
      - secrets.yml
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: password
  schedule.logger:
      enabled: true

#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
